from __future__ import annotations

from typing import Any


def default_mapping() -> dict[str, list[dict[str, Any]]]:
    return {
        "figures": [
            {
                "id": "Fig1",
                "title": "Dataset + environments + splits",
                "category": "main",
                "dest_name": "Fig1_dataset_envs.svg",
                "step_origin": "Step3-4",
                "source_key": "run_dir",
                "candidates": [
                    "figures/fig_split_sizes.svg",
                    "figures/fig_leakage_summary.svg",
                    "reports/split_summary.csv",
                ],
            },
            {
                "id": "Fig2",
                "title": "Generalization results",
                "category": "main",
                "dest_name": "Fig2_generalization.svg",
                "step_origin": "Step8",
                "source_key": "run_dir",
                "candidates": ["figures/fig_test_metrics.svg", "figures/fig_generalization_by_split.svg"],
            },
            {
                "id": "Fig3",
                "title": "Causal validation",
                "category": "main",
                "dest_name": "Fig3_causal_validation.svg",
                "step_origin": "Step9-10",
                "source_key": "cross_endpoint_dir",
                "candidates": [
                    "figures/fig_calibration_external.svg",
                    "figures/fig_roc_external.svg",
                    "figures/fig_pr_external.svg",
                    "figures/fig_zinv_env_predictability.svg",
                    "figures/fig_zinv_stability.svg",
                ],
            },
            {
                "id": "Fig4",
                "title": "Counterfactual SAR",
                "category": "main",
                "dest_name": "Fig4_counterfactual_sar.svg",
                "step_origin": "Step7",
                "source_key": "interpret_dir",
                "candidates": [
                    "figures/fig_counterfactual_top_edits.svg",
                    "figures/fig_cns_tradeoff.svg",
                    "figures/fig_rgroup_sar_top_series.svg",
                ],
            },
            {
                "id": "Fig5",
                "title": "Screening",
                "category": "main",
                "dest_name": "Fig5_screening.svg",
                "step_origin": "Step13-14",
                "source_key": "screen_analysis_dir",
                "candidates": ["figures/fig_triage_score_uncertainty_ad.svg", "figures/fig_diversity_tradeoff.svg"],
            },
            {
                "id": "FigS1",
                "title": "Ablations",
                "category": "supp",
                "dest_name": "FigS1_ablations.svg",
                "step_origin": "Step8",
                "source_key": "run_dir",
                "candidates": ["figures/fig_ablations.svg", "figures/fig_ablation_summary.svg"],
            },
            {
                "id": "FigS2",
                "title": "Robustness and conformal",
                "category": "supp",
                "dest_name": "FigS2_robustness.svg",
                "step_origin": "Step11",
                "source_key": "robust_dir",
                "candidates": ["figures/fig_seed_stability.svg", "figures/fig_conformal_coverage.svg"],
            },
            {
                "id": "FigS3",
                "title": "Interpretability extras",
                "category": "supp",
                "dest_name": "FigS3_interpretability.svg",
                "step_origin": "Step10",
                "source_key": "interpret_dir",
                "candidates": [
                    "figures/fig_rgroup_series_effects.svg",
                    "figures/fig_rgroup_effect_sizes.svg",
                    "figures/fig_fragment_enrichment.svg",
                ],
            },
            {
                "id": "FigS4",
                "title": "Screening diagnostics",
                "category": "supp",
                "dest_name": "FigS4_screening_diagnostics.svg",
                "step_origin": "Step13",
                "source_key": "screen_analysis_dir",
                "candidates": ["figures/fig_hit_score_distribution.svg", "figures/fig_pareto_score_uncertainty.svg"],
            },
            {
                "id": "FigS5",
                "title": "Feature match diagnostics",
                "category": "supp",
                "dest_name": "FigS5_feature_match.svg",
                "step_origin": "Step14",
                "source_key": "screen_match_dir",
                "candidates": [
                    "figures/fig_fragment_enrichment_hits_vs_library.svg",
                    "figures/fig_fragment_enrichment_hits.svg",
                    "figures/fig_shape_triangle_overlay.svg",
                    "figures/fig_shape_triangle_train_vs_hits.svg",
                ],
            },
        ],
        "tables": [
            {
                "id": "Table1",
                "title": "Dataset summary",
                "category": "main",
                "dest_name": "Table1_dataset_summary.csv",
                "step_origin": "Step3",
                "source_key": "run_dir",
                "candidates": ["reports/env_counts.csv", "reports/dataset_summary.csv"],
            },
            {
                "id": "Table2",
                "title": "Generalization metrics",
                "category": "main",
                "dest_name": "Table2_generalization_metrics.csv",
                "step_origin": "Step8",
                "source_key": "run_dir",
                "candidates": ["reports/test_metrics_summary.csv", "reports/metrics_summary.csv", "reports/generalization_metrics.csv"],
            },
            {
                "id": "Table3",
                "title": "Cross-endpoint metrics",
                "category": "main",
                "dest_name": "Table3_cross_endpoint_metrics.csv",
                "step_origin": "Step9",
                "source_key": "cross_endpoint_dir",
                "candidates": ["reports/cross_endpoint_metrics.csv", "reports/cross_endpoint_summary.csv", "reports/main_metrics.csv"],
            },
            {
                "id": "Table4",
                "title": "Top counterfactual edits",
                "category": "main",
                "dest_name": "Table4_counterfactual_edits.csv",
                "step_origin": "Step7",
                "source_key": "interpret_dir",
                "candidates": ["reports/counterfactual_top_edits.csv", "attribution/top_fragment_attributions.csv"],
            },
            {
                "id": "Table5",
                "title": "Top screening hits",
                "category": "main",
                "dest_name": "Table5_screening_hits.csv",
                "step_origin": "Step13-14",
                "source_key": "screen_analysis_dir",
                "candidates": ["selections/top50_risk_controlled.csv", "selections/top100_diverse.csv"],
            },
            {
                "id": "TableS1",
                "title": "Full ablation metrics",
                "category": "supp",
                "dest_name": "TableS1_ablation_metrics.csv",
                "step_origin": "Step8",
                "source_key": "run_dir",
                "candidates": ["reports/ablation_metrics.csv", "reports/ablation_summary.csv", "reports/ablation_grid.csv"],
            },
            {
                "id": "TableS2",
                "title": "Seed stability",
                "category": "supp",
                "dest_name": "TableS2_seed_stability.csv",
                "step_origin": "Step11",
                "source_key": "robust_dir",
                "candidates": [
                    "reports/seed_stability_summary.csv",
                    "reports/seed_metrics.csv",
                    "stability/seed_stability_metrics.csv",
                ],
            },
            {
                "id": "TableS3",
                "title": "Conformal coverage",
                "category": "supp",
                "dest_name": "TableS3_conformal_coverage.csv",
                "step_origin": "Step11",
                "source_key": "robust_dir",
                "candidates": [
                    "reports/conformal_summary.csv",
                    "reports/conformal_coverage_width.csv",
                    "conformal/conformal_coverage.csv",
                    "conformal/interval_width_by_split.csv",
                ],
            },
            {
                "id": "TableS4",
                "title": "Applicability domain bins",
                "category": "supp",
                "dest_name": "TableS4_ad_bins.csv",
                "step_origin": "Step11",
                "source_key": "robust_dir",
                "candidates": [
                    "reports/ad_bin_metrics.csv",
                    "reports/ad_metrics.csv",
                    "applicability_domain/error_vs_ad.csv",
                ],
            },
            {
                "id": "TableS5",
                "title": "R-group effects",
                "category": "supp",
                "dest_name": "TableS5_rgroup_effects.csv",
                "step_origin": "Step10",
                "source_key": "interpret_dir",
                "candidates": ["rgroup/rgroup_effects_full.csv", "rgroup/rgroup_effects.csv", "reports/rgroup_effects.csv"],
            },
            {
                "id": "TableS6",
                "title": "Fragment enrichment",
                "category": "supp",
                "dest_name": "TableS6_fragment_enrichment.csv",
                "step_origin": "Step10-14",
                "source_key": "screen_match_dir",
                "candidates": ["reports/fragment_enrichment_hits_vs_library.csv", "reports/fragment_overlap_with_zinv.csv"],
            },
            {
                "id": "TableS7",
                "title": "Screening novelty",
                "category": "supp",
                "dest_name": "TableS7_screening_novelty.csv",
                "step_origin": "Step13",
                "source_key": "screen_analysis_dir",
                "candidates": ["reports/novelty_report.csv", "reports/scaffold_novelty.csv"],
            },
            {
                "id": "TableS8",
                "title": "Chemotype panels",
                "category": "supp",
                "dest_name": "TableS8_chemotype_panels.csv",
                "step_origin": "Step14",
                "source_key": "screen_match_dir",
                "candidates": ["selections/chemotype_panels.csv", "reports/chemotype_summary.csv"],
            },
        ],
    }
